name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: [main, cicd]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: soootaleb
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      ############# MODEL ###############

      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version
          container_id=$(docker create soootaleb/hetic-data:0cfc9d2)
          docker cp "$container_id:/data/input.data.json" .
          docker cp "$container_id:/data/output.data.json" .
          pwd
          ls -l .

      ############ PYTHON #############
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn
      
      - name: execute py script # run file
        run: |
          ls -l .
          python train.py
          ls -l .

      ########### DOCKER ##################
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          file: Model.dockerfile
          # Note: tags has to be all lower-case
          tags: soootaleb/hetic-model:${{ steps.vars.outputs.sha_short }}
          # build on feature branches, push only on main branch
          push: true # ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}